repos:
  #  - repo: https://github.com/hadialqattan/pycln
  #    rev: v1.1.0 # Possible releases: https://github.com/hadialqattan/pycln/releases
  #    hooks:
  #      - id: pycln
  #        args: [--config=pyproject.toml]

  - repo: https://github.com/hadialqattan/pycln
    rev: v1.1.0
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.0.0
    hooks:
      - id: nbqa
        args: [pycln]
        name: nbqa-pycln
        alias: nbqa-pycln
        additional_dependencies: [pycln]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --expand-star-imports
          - --ignore-init-module-imports
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
      - id: trailing-whitespace
        files: "\\.(py|txt|yaml|json|md|toml|lock|cfg|html|sh|js|yml)$"
      - id: check-case-conflict
      #      - id: check-docstring-first
      - id: check-byte-order-marker
      - id: check-added-large-files
      - id: check-executables-have-shebangs

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]

  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args: [--in-place]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--config=pyproject.toml]
#  - repo: https://gitlab.com/pycqa/flake8
#    rev: "3.8.4"
#    hooks:
#      - id: flake8
#        additional_dependencies: [pep8-naming]
#
#  #  - repo: https://github.com/pre-commit/mirrors-mypy
#  #    rev: v0.782
#  #    hooks:
#  #      - id: mypy
#  #        exclude: tests/data/
#  #        args: [--config-file=pyproject.toml]
#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v2.6.0
#    hooks:
#      - id: pylint
#        args: [--rcfile=.pylintrc]
