name: conda-env
dependencies:
  - python=3.10
  - pygraphviz
  - pip
  - pip:
    - dill
    - python-dotenv
    - bloom-filter
    - flask_socketio
    - docker
    - pre-commit
    - graphviz
    - tabulate
    - flask
    - flask_cors
    - python-socketio
    - aenum
    - treelib
