name: crome
channels:
  - defaults
dependencies:
  - python=3.9
  - pygraphviz
  - dill
  - graphviz
  - tabulate
  - flask
  - flask_cors
  - python-socketio
  - aenum
  - treelib
  - pip:
      - python-dotenv
      - bloom-filter
      - flask_socketio
      - docker
      - pre-commit
