name: crome
channels:
  - conda-forge
  - defaults
dependencies:
  - atk-1.0=2.36.0
  - ca-certificates=2021.10.26
  - cairo=1.16.0
  - certifi=2021.10.8
  - dill=0.3.4
  - expat=2.4.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.6
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gobject-introspection=1.68.0
  - graphite2=1.3.14
  - graphviz=2.48.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=2.8.1
  - icu=68.2
  - jbig=2.1
  - jpeg=9d
  - lerc=2.2.1
  - libcxx=12.0.0
  - libdeflate=1.7
  - libffi=3.4.2
  - libgd=2.2.5
  - libiconv=1.16
  - libpng=1.6.37
  - librsvg=2.50.7
  - libtiff=4.3.0
  - libtool=2.4.6
  - libwebp=1.2.1
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - ncurses=6.3
  - ninja=1.10.2
  - openssl=1.1.1m
  - pango=1.48.7
  - pcre=8.45
  - pip=21.2.4
  - pixman=0.40.0
  - pygraphviz=1.7
  - python=3.9.7
  - python_abi=3.9
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.37.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - aenum==3.1.6
    - bidict==0.21.4
    - bloom-filter==1.3.3
    - cfgv==3.3.1
    - charset-normalizer==2.0.10
    - click==8.0.3
    - distlib==0.3.4
    - docker==5.0.3
    - filelock==3.4.2
    - flask==2.0.2
    - flask-cors==3.0.10
    - flask-socketio==5.1.1
    - future==0.18.2
    - identify==2.4.4
    - idna==3.3
    - itsdangerous==2.0.1
    - jinja2==3.0.3
    - markupsafe==2.0.1
    - nodeenv==1.6.0
    - platformdirs==2.4.1
    - pre-commit==2.17.0
    - pyeda==0.28.0
    - python-dotenv==0.19.2
    - python-engineio==4.3.1
    - python-graphviz==0.19.1
    - python-socketio==5.5.1
    - pyyaml==6.0
    - requests==2.27.1
    - six==1.16.0
    - tabulate==0.8.9
    - toml==0.10.2
    - treelib==1.6.1
    - urllib3==1.26.8
    - virtualenv==20.13.0
    - websocket-client==1.2.3
    - werkzeug==2.0.2
