name: crome-legacy

channels:
  - default
  - conda-forge

dependencies:
  - python=3.10
  - pygraphviz
  - spot
  - pip
  - pip:
    - dill
    - python-dotenv
    - bloom-filter
    - pyeda
    - ipython
#    - flask_socketio
    - docker
    - pre-commit
    - graphviz
    - tabulate
#    - flask
#    - flask_cors
#    - python-socketio
    - aenum
    - treelib
