name: envs
channels:
  - defaults
dependencies:
  - python=3.9
  - pygraphviz
  - dill
  - graphviz
  - tabulate
  - docker
  - flask
  - python-dotenv
  - flask_cors
  - flask_socketio
  - python-socketio
  - pre-commit
  - bloom-filter
  - aenum
  - treelib
